config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".

  Spree::Core::Engine.add_routes do
    post '/mercado_pago/checkout', to: "mercado_pago#checkout", as: :mercado_pago_checkout
    get  '/mercado_pago/success', to: "mercado_pago#success", as: :mercado_pago_success
    get  '/mercado_pago/failure', to: "mercado_pago#failure", as: :mercado_pago_failure
    post '/mercado_pago/ipn', to: "mercado_pago#ipn", as: :mercado_pago_ipn
    get '/recently_viewed_products' => 'products#recently_viewed'
    get '/get_body_taxonomy_results' => 'home#get_body_taxonomy_results'

    namespace :admin do
      get '/cms', to: "cms#index", as: :cms_form
      get '/cms/banner-top', to: "cms#banner_top", as: :banner_top_index
      post '/cms/banner-top', to: "cms#banner_top_update", as: :banner_top_update
    end
  end

  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spree/payment_method/mercado_pago.rb
module Spree
  class PaymentMethod::MercadoPago < PaymentMethod

    def payment_profiles_supported?
      false
    end

    def provider_class
      ::MercadoPago::Client
    end

    def provider(additional_options = {})
      @provider ||= begin
                      options = { sandbox: preferred_sandbox }
                      client = provider_class.new(self, options.merge(additional_options))
                      client.authenticate
                      client
                    end
    end

    def source_required?
      false
    end

    def auto_capture?
      false
    end

    def preferred_sandbox
      Rails.application.try(:secrets).try(:[], :mercadopago).try(:[], "sandbox")
    end

    ## Admin options

    def can_void?(payment)
      payment.state != 'void'
    end

    def actions
      %w{void}
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    def self.find_by_array_of_ids(ids)
      where(id: ids)
    end
  end
end

app/controllers/spree/admin/cms_controller.rb
module Spree
  module Admin
    class CmsController < Spree::Admin::BaseController
      def index
        render 'spree/admin/cms/index'
      end

      def banner_top
        @banner_top = BannerTop.find_by id: 1

        render 'spree/admin/cms/cms_banner_top'
      end

      def banner_top_update
        description = params[:banner_top][:description]
        button_text = params[:banner_top][:button_text]
        button_link = params[:banner_top][:button_link]

        @banner_top = BannerTop.find_by id: 1


        if @banner_top
          @banner_top.update(
            description: description,
            button_text: button_text,
            button_link: button_link
          )
        else
          @banner_top.create(
            description: description,
            button_text: button_text,
            button_link: button_link
          )
        end

        flash[:success] = Spree.t('update_banner_first_home')
        redirect_to action: 'banner_top'
      end
    end
  end
end

app/controllers/spree/helpers/spree/base_helper_decorator.rb
module Spree
  BaseHelper.module_eval do
    def cached_recently_viewed_products_ids
      (cookies['recently_viewed_products'] || '').split(', ')
    end

    def cached_recently_viewed_products
      Spree::Product.find_by_array_of_ids(cached_recently_viewed_products_ids)
    end
  end
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do

  def index
    # First Slider
    @slider_piel = Spree::Taxon.where(:name => 'Piel').first
    @slider_piel_products = @slider_piel.products.limit(3).active if @slider_piel
    @slider_rostro = Spree::Taxon.where(:name => 'Rostro').first
    @slider_rostro_products = @slider_rostro.products.limit(3).active if @slider_rostro
    @slider_novedades = Spree::Taxon.where(:name => 'Novedades').first
    @slider_novedades_products = @slider_novedades.products.limit(10).active if @slider_novedades
    @first_banner_home = BannerTop.find(1)
    @taxo_ojos = Spree::Taxon.where(:name => 'Ojos').first
    @products_ojos = @taxo_ojos.products.limit(4).active if @taxo_ojos
  end

  def get_body_taxonomy_results
    taxo = Spree::Taxon.where(:name => params[:taxonomy]).first
    products = taxo.products.limit(4).active if taxo
    render 'spree/shared/_body_taxonomy_results', layout: false, :locals => {:results => products, :results_taxo => taxo}
  end

end

app/controllers/spree/mercado_pago_controller.rb
module Spree
  class MercadoPagoController < StoreController
    protect_from_forgery except: :ipn
    skip_before_action :set_current_order, only: :ipn

    def checkout
      if current_order.state_name != :payment
        redirect_to spree.cart_path and return false
      end

      payment_method = PaymentMethod::MercadoPago.find(params[:payment_method_id])
      payment = current_order.payments.create!({amount: current_order.total, payment_method: payment_method})
      payment.started_processing!

      preferences = ::MercadoPago::OrderPreferencesBuilder.
        new(current_order, payment, callback_urls).
        preferences_hash

      provider = payment_method.provider
      provider.create_preferences(preferences)

      redirect_to provider.redirect_url
    end

    # Success/pending callbacks are currently aliases, this may change
    # if required.
    def success
      if params["collection_status"] == "approved"
        # NOTE SE VALIDA QUE EL PAGO NO SE HAYA COMPLETADO POR IPN
        unless payment.state == "completed"
          payment.complete!
          payment.order.next
        end

        flash.notice = Spree.t(:order_processed_successfully)
        flash['order_completed'] = true
      end

      if params["collection_status"] == "pending"
        unless payment.state == "pending"
          payment.pend!
          payment.order.next unless payment.order.state == "complete"
        end

        flash.notice = Spree.t(:payment_processing_pending)
        flash['order_completed'] = false
      end

      redirect_to spree.order_path(payment.order)
    end

    def failure
      payment.failure!
      flash.alert = Spree.t(:payment_processing_failed)
      flash['order_completed'] = false
      redirect_to spree.cart_path
    end

    def ipn
      begin
        logger = Logger.new("#{Rails.root}/log/ipn_notifications.log", 'daily')
        logger.info("-----------------------------------------")
        logger.info("Iniciando recepción de notificaciones IPN")
        logger.info("--------------------")
        logger.info("Datos de la operacion:...Operation id:...#{params[:id]}....Topic:...#{params[:topic]}....")
        logger.info("Datos de los parametros:...params...#{params}...")
        logger.info("Datos de la request:..URL:..#{request.url}..POST:..#{request.post?}...")

        notification = MercadoPago::Notification.
          new(operation_id: params[:id], topic: params[:topic])

        if notification.save
          begin
            MercadoPago::HandleReceivedNotification.new(notification).process!
            logger.info("Notificacion procesada correctamente")
          rescue Exception => a
            logger.debug("Error al procesar la notificación.")
            logger.debug("Error: #{a.to_s}")
            logger.debug("Error: #{a.backtrace.to_s}")
          end
        end

        logger.info("--------------------")
        logger.info("Devolviendo STATUS 200 OK")
      rescue Exception => e
        logger.debug("Error al guardar la notificación")
        logger.debug("Error: #{e.to_s}")
        logger.info("--------------------")

        logger.info("Devolviendo igualmente, STATUS 200 OK")
      end
      logger.info("-----------------------------------------")

      render nothing: true, status: 200, content_type: "text/html"
    end

    private

    def payment
      @payment ||= Spree::Payment.where(number: params[:external_reference]).
        first
    end

    def callback_urls
      @callback_urls ||= {
        success: mercado_pago_success_url,
        pending: mercado_pago_success_url,
        failure: mercado_pago_failure_url
      }
    end
  end
end

app/controllers/spree/products_controller_decorator.rb
module Spree
  ProductsController.class_eval do
    skip_before_action :set_current_order, only: :recently_viewed
    after_action :save_recently_viewed, only: :recently_viewed

    def recently_viewed
      render 'spree/products/recently_viewed', layout: false
    end

    private

    def save_recently_viewed
      id = params[:product_id]
      return unless id.present?

      rvp = (cookies['recently_viewed_products'] || '').split(', ')
      rvp.delete(id)
      rvp << id unless rvp.include?(id.to_s)
      rvp_max_count = 10
      rvp.delete_at(0) if rvp.size > rvp_max_count.to_i
      cookies['recently_viewed_products'] = rvp.join(', ')
    end
  end
end

app/views/spree/checkout/_address.html.erb
<div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
    <div class="panel panel-default" id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
    <div class="panel panel-default" id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
        </div>
        <div class="panel-body">
          <p class="field checkbox" data-hook="use_billing">
            <%= label_tag :order_use_billing, id: 'use_billing' do %>
              <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
              <%= Spree.t(:use_billing_address) %>
            <% end %>
          </p>
          <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-pink' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address" class='save-user-address-wrapper'>
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="panel panel-default" id="order_details" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="panel-body">
    <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <% if @order.using_store_credit? %>
    <%= button_tag Spree.t('store_credit.remove'), name: 'remove_store_credit', class: 'continue btn' %>
  <% end %>
  <%= submit_tag Spree.t(:place_order), class: 'btn btn-lg btn-success' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_delivery.html.erb
<div class="panel panel-default" id='shipping_method' data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:delivery) %></h3>
  </div>
  <div class="panel-body" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>
        <div class="shipment">
          <h4 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h4>

          <table class="table stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <tr class="active">
                <th></th>
                <th align='left'><%= Spree.t(:item) %></th>
                <th><%= Spree.t(:qty) %></th>
                <th><%= Spree.t(:price) %></th>
              </tr>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h4 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h4>
          <ul class="list-group shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="list-group-item shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id, data: { behavior: 'shipping-method-selector', cost: rate.display_cost } %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="badge rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <h4><%= Spree.t(:shipping_instructions) %></h4>
        <%= form.text_area :special_instructions, cols: 40, rows: 4, class: "form-control" %>
      </p>
    <% end %>
  </div>
</div>

<br />

<div data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-pink' %>
</div>

<%= javascript_include_tag 'spree/frontend/checkout/shipment' %>

app/views/spree/checkout/_payment.html.erb
<div class="panel panel-default" id="payment" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:payment_information) %></h3>
  </div>
  <div class="panel-body" data-hook="checkout_payment_step">
    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= Spree.t(:use_existing_cc) %>
        </label>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= Spree.t(:use_new_cc_or_payment_method) %>
        </label>
      </div>

      <div id="existing_cards">
        <p class="form-group" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %> / <%= card.year %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <%= render partial: 'spree/checkout/payment/storecredit' %>

    <ul class="list-group" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li class="list-group-item radio">
          <label>
            <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <ul class="nav" id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.method_type}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>


    <% if Spree::Frontend::Config[:coupon_codes_enabled] %>
      <p class='field' data-hook='coupon_code'>
        <%= form.label :coupon_code %>
        <%= form.text_field :coupon_code, class: 'form-control' %>
      </p>
    <% end %>
  </div>
</div>

<div data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-pink' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_summary.html.erb
<h3><%= Spree.t(:order_summary) %></h3>

<table class="table" data-hook="order_summary">
  <tbody>
    <tr data-hook="item_total">
      <td><%= Spree.t(:item_total) %>:</td>
      <td><%= order.display_item_total.to_html %>:</td>
    </tr>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <tbody data-hook="order_details_promotion_adjustments">
        <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tbody data-hook="order_details_tax_adjustments">
      <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %></td>
          <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
        </tr>
      <% end %>
    </tbody>

    <% if order.passed_checkout_step?("address") && order.shipments.any? %>
      <tr data-hook="shipping_total">
        <td><%= Spree.t(:shipping_total) %>:</td>
        <% shipping_total = Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency) %>
        <td data-hook='shipping-total' data-currency='<%= Money::Currency.find(order.currency).symbol %>' thousands-separator='<%= shipping_total.thousands_separator %>' decimal-mark='<%= shipping_total.decimal_mark %>'><%= shipping_total.to_html %></td>
      </tr>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_shipment_promotion_adjustments">
          <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %>:</td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.eligible.exists? %>
      <tbody id="summary-order-charges" data-hook>
        <% order.adjustments.nonzero.eligible.each do |adjustment| %>
        <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
          <tr class="total">
            <td><%= adjustment.label %>:</td>
            <td><%= adjustment.display_amount.to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tr data-hook="order_total">
      <td><%= Spree.t(:order_total) %>:</td>
      <td>
        <span id='summary-order-total' class="lead text-primary" data-currency="<%= Money::Currency.find(order.currency).symbol %>"><%= order.display_total.to_html %></span>
      </td>
    </tr>

    <% if order.using_store_credit? %>
      <tr data-hook="order_details_store_credit">
        <td><%= Spree.t(:store_credit_name) %>:</td>
        <td><span id='summary-store-credit'><%= order.display_total_applied_store_credit.to_html %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/checkout/edit.html.erb
<% @body_id = 'checkout-page' %>

<div class='Checkout PaddingSides --vertical'>

  <div id="checkout" data-hook>
    <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

    <div data-hook="checkout_header">
      <div>
        <h1 data-hook="checkout_title"><%= Spree.t(:checkout) %></h1>
      </div>
      <div data-hook="checkout_progress">
        <%= checkout_progress %>
      </div>
    </div>

    <div data-hook="checkout_content">
      <div data-hook="checkout_form_wrapper">
        <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
          <% if @order.state == 'address' || !@order.email? %>
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="form-group">
                  <%= form.label :email %>
                  <%= form.email_field :email, class: 'form-control', required: true %>
                </div>
              </div>
            </div>
          <% end %>
          <%= form.hidden_field :state_lock_version %>
          <%= render @order.state, form: form %>
        <% end %>
      </div>
      <% if @order.state != 'confirm' %>
        <div id="checkout-summary" data-hook="checkout_summary_box">
          <%= render partial: 'summary', locals: { order: @order } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  Spree.current_order_id = "<%= @order.number %>"
  Spree.current_order_token = "<%= @order.token %>"
</script>

app/views/spree/checkout/registration.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
<div id="registration" class="row" data-hook>
  <div id="account" class="col-xs-12 col-sm-6 AuthView">
    <div id="new-customer" class="card-body" data-hook="login">
      <h1><%= Spree.t(:registration) %></h1>
      <%= form_for @user, :as => :spree_user, :url => spree.registration_path(@user) do |f| %>
        <div data-hook="signup_inside_form">
          <%= render :partial => 'spree/shared/user_form', :locals => { :f => f } %>
          <div class='button-wrapper'>
            <%= f.submit Spree.t(:create), :class => 'ButtonRadius --shadow --small --pink' %>
          </div>
        </div>
      <% end %>
      <div class="text-center" style='margin-bottom: 20px'>
        <%= Spree.t(:or) %>
          <%= link_to Spree.t(:login_as_existing), spree.login_path %>
      </div>
      <div data-hook="login_extras"></div>
    </div>
  </div>
  <% if Spree::Config[:allow_guest_checkout] %>
    <div class="col-xs-12 col-sm-6 AuthView">
      <div class="card">
        <h1><%= Spree.t(:guest_user_account) %></h1>
        <%= form_for @order, :url => update_checkout_registration_path, :method => :put, :html => { :id => 'checkout_form_registration' } do |f| %>
          <div class="form-group">
            <%= f.label :email, Spree.t(:email), class: 'required', title: 'required' %>
            <%= f.email_field :email, :class => 'form-control title', :placeholder => Spree.t(:email) %>
          </div>
          <div class='button-wrapper'>
            <%= f.submit Spree.t(:continue), :class => 'ButtonRadius --shadow --small --pink' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>